version: '2'
services:
  app:
    container_name: deelbe_service
    image: deelbe_service
    build: .
    networks:
      - main_network
    ports:
      - "3001:3001"
    volumes:
      # - ${PWD}/app/node_modules
      - /app/node_modules
      - .:/app
    stdin_open: true

volumes:
  node_modules:

networks:
  main_network:
    driver: bridge